### ISSUE TITLE
Training Error (Model object has no attribute '_check_num_samples')

### ISSUE THREAD

**Issue by koido** [alshedivat/keras-gp#16]
Hi, I'm very interested in your algorithm.
I downloaded the latest keras-gp codes, using keras v2.0.2.

When calling example codes, *_actuator.py, I get following error message:

> Training...
Traceback (most recent call last):
  File "./gp_lstm_actuator.py", line 109, in <module>
    main()
  File "./gp_lstm_actuator.py", line 93, in main
    epochs=epochs, batch_size=batch_size, verbose=2)
  File "/home/myname/opt/kgp/kgp/utils/experiment.py", line 67, in train
    **fit_kwargs)
  File "/home/myname/opt/kgp/kgp/models.py", line 128, in fit
    **kwargs)
  File "/home/myname/opt/anaconda2-4.3.0/lib/python2.7/site-packages/keras/engine/training.py", line 1485, in fit
    initial_epoch=initial_epoch)
  File "/home/myname/opt/kgp/kgp/tweaks.py", line 72, in _fit_loop
    num_train_samples = self._check_num_samples(ins, batch_size,
AttributeError: 'Model' object has no attribute '_check_num_samples'

Keras itself works fine.
I cannot run other example codes, because I cannot find how to make kin40k.npz optimized for your sample codes from original kin40k datasets (sorry, it is other problem for me...)
Could you advise me if other information for my environment is required?

Best regards.
Masaru.

**Comment by alshedivat** [comment]
Please update your Keras to the latest version. While Keras API is stable, `keras-gp` overwrites some internal functionality (e.g., the `_fit_loop` function), which slightly changes over time. The current goal is to keep `keras-gp` compatible with the latest stable version of Keras.

Regarding `kin40k.npz`, you can download it from [here](https://yadi.sk/d/n7zI4bfb3RiUHW).

**Comment by laysantena** [comment]
try this. it worked for me.

pip install -r requirements.txt
[requirements.txt](https://github.com/alshedivat/keras-gp/files/2635964/requirements.txt)
