### ISSUE TITLE
How can I get one standard deviation of the predictive distributions?

### ISSUE THREAD

**Issue by WilesDai** [alshedivat/keras-gp#26]
In the Figure 5 of paper "Learning Scalable Deep Kernels with Recurrent Structure", predictive uncertainty of the GP-LSTM model is showed by contour plots and error-bars; the latter denote one standard deviation of the predictive distributions.
My question is how can I get one standard deviation of the predictive distributions when using keras-gp? I haven't found any interface function to get the standard deviation of the predictive distributions. Would you please help solve this problem?

**Comment by WilesDai** [comment]
Very sorry, by the parameter "return_var" of the model.predict()? I'm too careless.

**Comment by alshedivat** [comment]
Yes, `return_var` should return the predictive variances. given the predictive mean and variance at each point, you can reconstruct the full predictive Gaussian distribution (as we did for the plots).
