### ISSUE TITLE
ImportError: cannot import name '_to_list' from 'keras.engine.topology'

### ISSUE THREAD

**Issue by rbnvrw** [alshedivat/keras-gp#31]
I'm trying to add a GP layer to my RNN layer that I use as generator network in a GAN.

I used the example code from the repository, but got the following error:
```
Using GPML backend with Octave engine as the default one.
Traceback (most recent call last):
  File "3ddiffusion.py", line 20, in <module>
    from kgp.layers import GP
  File "/home/ruben/repositories/kgp/kgp/__init__.py", line 9, in <module>
    from . import models
  File "/home/ruben/repositories/kgp/kgp/models.py", line 13, in <module>
    from keras.engine.topology import _to_list
ImportError: cannot import name '_to_list' from 'keras.engine.topology'
```

Do you have any idea what is wrong? Thank you!

**Comment by alshedivat** [comment]
Which Keras version do you use? Some functionality of kgp uses some internal functionality in Keras (which probably has changed over time); `kgp` requires `keras==2.1.3`.

**Comment by rbnvrw** [comment]
Thank you. I now installed keras 2.1.3 and have tensorflow 2.1.0

The error disappears, but now it seems the version of tensorflow is probably too recent:
```
model = Sequential()
  File "/home/ruben/anaconda3/envs/defpy/lib/python3.7/site-packages/keras/models.py", line 405, in __init__
    name = prefix + str(K.get_uid(prefix))
  File "/home/ruben/anaconda3/envs/defpy/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 68, in get_uid
    graph = tf.get_default_graph()
AttributeError: module 'tensorflow' has no attribute 'get_default_graph'
```

Do you have any plans of updating the repository to support the current keras/tensorflow versions or is the only option to downgrade (and to which version?)?

**Comment by alshedivat** [comment]
As of now, there's no plan for upgrades/support for newer versions of TF and Keras on my side. But I'm very open to contributions and happy to support interested contributors (e.g, do code review, provide feedback, etc.).

Also, just wanted to point out that alternative, more mature libraries have been developed over the past few years: [GPFlow 2.0](https://github.com/GPflow/GPflow) (based on TF2), [GPyTorch](https://gpytorch.ai/) (based on PyTorch 1.0+), [edward2](https://github.com/google/edward2) ([implements GP layers](https://github.com/google/edward2/blob/master/edward2/tensorflow/layers/gaussian_process.py#L264-L330) for TF2 and is compatible with Keras).

The biggest advantage of `keras-gp` is that it uses GPML library under the hood, which is perhaps the most feature-complete library for GPs (although written in MATLAB, and is slowly getting outdated). Unless you need some specific features from GPML or simply want to reproduce experiments from our JMLR paper, I would recommend using one of the libraries I mentioned above.

**Comment by rbnvrw** [comment]
Great! I understand. Thank you for pointing me towards relevant other projects. I'll have a look!
